EAD_Assignment_3/Models/User.cs
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Drawing.Imaging;
using System.ComponentModel.DataAnnotations;

namespace EAD_Assignment_3.Models
{
    public class User
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter name")]
        [StringLength(50)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter email")]
        [StringLength(50)]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter password")]
        [StringLength(50)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please enter password again")]
        [StringLength(50)]
        public string Retype_Password { get; set; }
    }
    public class User1
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter name")]
        [StringLength(50)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter password")]
        [StringLength(50)]
        public string Password { get; set; }

    }
}

EAD_Assignment_3/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EAD_Assignment_3.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EAD_Assignment_3.Controllers
{
    public class PostController : Controller
    {
        [HttpGet]
        public ViewResult PostForm(int id)
        {
            ViewBag.id = id;
            return View();
        }
        public ViewResult PostDetails(int postUId)
        {
            int? userId = HttpContext.Session.GetInt32("signIn");
            PostRepository pR = new PostRepository();
            Post post = pR.getPost(userId);
            return View("PostDetails",post);
        }
        [HttpPost]
        public ViewResult PostForm(Post p,int id)
        {
            ViewBag.id = id;
            PostRepository pR = new PostRepository();

            if (ModelState.IsValid)
            {
                string check = pR.AddPost(p,id);
                if (check.Equals("post added"))
                {
                    List<Post> posts = pR.getAllPosts();
                    return View("../User/HomeScreen",posts);
                }
                else if (check.Equals("post not added"))
                {
                    ModelState.AddModelError(String.Empty, "Your post could not be added.Try again!");
                    return View();
                }
                return View();
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Please enter correct data");
                return View();
            }
        }
        public ViewResult Remove(int id)
        {
            PostRepository pR = new PostRepository();
            int? userId = HttpContext.Session.GetInt32("signIn");
            bool result = pR.deletePost(userId);
            if(result)
            {
                List<Post> posts = pR.getAllPosts();
                return View("../User/HomeScreen", posts);
            }
            List<Post> post = pR.getAllPosts();
            return View("../User/HomeScreen", post);
        }

        public ViewResult Edit()
        {
            PostRepository pr = new PostRepository();
            int? userId = HttpContext.Session.GetInt32("signIn");
            Post post = pr.getPost(userId);
            return View("Edit", post);

        }

        [HttpPost]
        public ViewResult Edit(Post p)
        {
            if (ModelState.IsValid)
            {
                UserRepository uR = new UserRepository();
                PostRepository pR = new PostRepository();
                bool result =pR.updatePost(p);
                if (result)
                {
                    List<Post> posts = pR.getAllPosts();
                    return View("../User/HomeScreen", posts);
                }
                else
                {
                    ModelState.AddModelError(String.Empty, "Try Again.");
                    return View();
                }
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Please enter correct data");
                return View();
            }
        }
    }
}

EAD_Assignment_3/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EAD_Assignment_3.Models;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Http;

namespace EAD_Assignment_3.Controllers
{
    public class UserController : Controller
    {
        [HttpGet]
        public ViewResult SignUp()
        {

            return View();
        }
        [HttpGet]
        public ViewResult SignIn()
        {

            return View();
        }
        [HttpPost]
        public ViewResult SignUp(User u)
        {
            UserRepository uR=new UserRepository();
            
            if (ModelState.IsValid)
            {
                string check = uR.AddUser(u);
                if(check.Equals("user added"))
                {
                    return View("SignIn");
                }
                else if (check.Equals("user exist"))
                {
                    ModelState.AddModelError(String.Empty, "This username already exist.");
                    return View();
                }
                else if (check.Equals("user not added"))
                {
                    ModelState.AddModelError(String.Empty, "Please try again!");
                    return View();
                }
                else if (check.Equals("password not matched"))
                {
                    ModelState.AddModelError(String.Empty, "Password not matched");
                    return View();
                }
                return View();
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Please enter correct data");
                return View();
            }

        }
        [HttpPost]
        public ViewResult SignIn(User1 u)
        {
            UserRepository uR = new UserRepository();
            PostRepository pR = new PostRepository();
            if (ModelState.IsValid)
            {
                var value = uR.SignInUser(u);
                if (value.check.Equals("user exist"))
                {
                    int userId = uR.getId(u.Name);
                    HttpContext.Session.SetInt32("signIn", userId);
                    ViewBag.id = value.id;
                    List<Post> posts = pR.getAllPosts();
                    return View("HomeScreen",posts);
                }
                else if (value.check.Equals("admin"))
                {
                    List<User> users = uR.getAllUsers();
                    return View("../Admin/AdminForm", users);
                }
                else if (value.check.Equals("user not exist"))
                {
                    ModelState.AddModelError(String.Empty, "Your password or username is wrong.");
                    return View();
                }
                return View();
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Please enter correct data");
                return View();
            }

        }
        public ViewResult HomeScreen()
        {
            PostRepository pR = new PostRepository();
            List<Post> posts = pR.getAllPosts();
            return View("HomeScreen", posts);
        }

        public ViewResult About()
        {
            return View();
        }
        public ViewResult Edit()
        {
            User u = new User();
            if (HttpContext.Session.Keys.Contains("signIn"))
            {
                UserRepository user = new UserRepository();
                int? userId = HttpContext.Session.GetInt32("signIn");
                u= user.getUser(userId);
            }
            return View("Edit", u);
        }

        [HttpPost]
        public ViewResult Edit(User u)
        {
            if (ModelState.IsValid)
            {
                UserRepository uR = new UserRepository();
                PostRepository pR = new PostRepository();
                bool result = uR.updateUser(u);
                if (result)
                {
                    List<Post> posts = pR.getAllPosts();
                    return View("HomeScreen", posts);
                }
                else
                {
                    ModelState.AddModelError(String.Empty, "Try Again.");
                    return View();
                }
            }
            else
            {
                ModelState.AddModelError(String.Empty, "Please enter correct data");
                return View();
            }
        }
    }
}

EAD_Assignment_3/Views/User/About.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>About Page</h1>

EAD_Assignment_3/Views/User/Edit.cshtml
@model EAD_Assignment_3.Models.User
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="post" asp-action="Edit">

    <div asp-validation-summary="ModelOnly"></div>

    <div>
        <label class="form-label" asp-for="Id"></label><br>
        <input class="form-control" asp-for="Id" readonly><br>

    </div>

    <div>
        <label class="form-label" asp-for="Name"></label><br>
        <input class="form-control" asp-for="Name"><br>
        <span asp-validation-for="Name"></span>
    </div>
    <div>
        <label class="form-label" asp-for="Email"></label><br>
        <input class="form-control" asp-for="Email"><br>
        <span asp-validation-for="Email"></span>
    </div>
    <div>
        <label class="form-label" asp-for="Password"></label><br>
        <input class="form-control" asp-for="Password"><br>
        <span asp-validation-for="Password"></span>
    </div>
    <div>
        <label class="form-label" asp-for="Retype_Password"></label><br>
        <input class="form-control" asp-for="Retype_Password"><br>
        <span asp-validation-for="Retype_Password"></span>
    </div>
    <input class="btn btn-dark" type="submit" value="Update" />

</form>

EAD_Assignment_3/Views/User/HomeScreen.cshtml
@model List<EAD_Assignment_3.Models.Post>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<html>
    <head>
        <title>Home Page</title>
        <link href="~/css/site.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
    </head>

    <body class="bg-primary">*@
<div class="p-1"><a asp-controller="Post" asp-action="PostForm" asp-route-id=@ViewBag.id class=" btn btn-dark ">Create Post</a></div>
@if (Model.Count >= 1)
{
    @foreach (EAD_Assignment_3.Models.Post p in Model)
    {
        <div class="bg-warning rounded-pill border border-5 border border-dark">
            <h2 class="text-center p-3"><a asp-controller="Post" asp-action="PostDetails" asp-route-id="@p.UserId">@p.Title</a></h2><br />
            <p class="text-center">@p.Content</p>
        </div>

    }
}
@*</body>
    </html>*@

EAD_Assignment_3/Views/User/SignIn.cshtml
@using EAD_Assignment_3.Models
@model User1
<html>
<head>
    <title>SignIn</title>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
</head>

<body class="bg-success">
    <form method="post" asp-controller="User" asp-action="SignIn">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="bg-success">
                <div class="col-md-4">
                    <label asp-for="Name" class="form-label"></label><br>
                    <input asp-for="Name" class="form-control"><br>
                    <span asp-validation-for="Name" class="alert-danger"></span>
                </div>
                <div class="col-md-4">
                    <label asp-for="Password" class="form-label"></label><br>
                    <input type="password" asp-for="Password" class="form-control"><br>
                    <span asp-validation-for="Password" class="alert-danger"></span>
                </div>
                <input type="submit" value="SignIn" class="btn badge-dark" />
            </div>
    </form>
    <div>
        <p>If Account doesn't exit then <a asp-controller="User" asp-action="SignUp" class="btn btn-dark">SignUp</a></p>
    </div>
</body>
</html>

EAD_Assignment_3/Views/User/SignUp.cshtml
@using EAD_Assignment_3.Models
@model User
<html>
<head>
    <title>SignUp</title>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap-grid.css" rel="stylesheet" />
</head>

<body class="bg-success">

    <form method="post" asp-action="SignUp" class="col g-3">
        <div asp-validation-summary="ModelOnly"></div>
        <div class="col-md-4">
            <label asp-for="Name" class="form-label"></label><br>
            <input asp-for="Name" class="form-control"><br>
            <span asp-validation-for="Name" class="alert-danger"></span>
        </div>

        <div class="col-md-4">
            <label asp-for="Email" class="form-label"></label><br>
            <input asp-for="Email" class="form-control"><br>
            <span asp-validation-for="Email" class="alert-danger"></span>
        </div>

        <div class="col-md-4">
            <label asp-for="Password" class="form-label"></label><br>
            <input type="password" asp-for="Password" class="form-control"><br>
            <span asp-validation-for="Password" class="alert-danger"></span>
        </div>

        <div class="col-md-4">
            <label asp-for="Retype_Password" class="form-label"></label><br>
            <input type="password" asp-for="Retype_Password" class="form-control"><br>
            <span asp-validation-for="Retype_Password" class="alert-danger"></span>
        </div>


        <input type="submit" value="SignUp" class="btn badge-dark" />

    </form>
</body>
</html>